[package]
name = "orderbook"
version = "0.1.0"
authors = ["Hiroki Tanaka <support@sencoinex.com>"]
license = "MIT"
repository = "https://github.com/sencoinex/orderbook"
edition = "2021"

[dependencies]
